### ISSUE TITLE
cedar-10 is going to be end of life

### ISSUE THREAD

**Issue by dmlond** [Uvize/heroku-buildpack-apache-passenger-shibboleth#1]
cedar-10 is going away in November 2015.  cedar-14 uses libssl.so 1.0 instead of 0.9.8.  The shibboleth daemon that you packaged requires ssl 0.9.8.  The shibboleth application needs to be updated to one that uses ssl 1.0.

**Comment by jsanders** [comment]
Yep, thanks, making this work for cedar-14 has been on my todo list for awhile, but I appreciate you making an issue to track it! It will definitely require re-compiling things.

**Comment by jsanders** [comment]
Just pushed some changes for cedar-14 compatibility. Thanks again for reporting this!
